spring.application.name=Suitus
file.upload-dir=src/main/resources/static/uploads/
spring.mvc.hiddenmethod.filter.enabled=true
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:postgresql://localhost:5432/shungo
spring.datasource.username=postgres
spring.datasource.password=61701635
spring.datasource.hikari.connection-timeout: 15000
spring.datasource.hikari.maximum-pool-size: 3

logging.level.root=WARN
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR